import { SHIFTS, cycleDurationMs, formatDuration, formatClock, getShiftWindow, projectCycles, nextCycleEnd } from './calculations.js';

const KEY = 'application-bobines-v1';
let state = JSON.parse(localStorage.getItem(KEY) || '{"shiftId":"morning","lines":[]}');
let editingId = null; let installPrompt;
const $ = (s) => document.querySelector(s);
const save = () => localStorage.setItem(KEY, JSON.stringify(state));
const lineById = (id) => state.lines.find((line) => line.id === id);
function render() {
  const window = getShiftWindow(state.shiftId); $('#shift-range').textContent = `${window.start} → ${window.end}`.replace(/.*?(\d{2}:\d{2}).*?(\d{2}:\d{2}).*/, '$1 → $2');
  $('#shift-options').innerHTML = SHIFTS.map((shift) => `<button class="shift-option ${shift.id === state.shiftId ? 'selected' : ''}" data-shift="${shift.id}" role="radio" aria-checked="${shift.id === state.shiftId}">${shift.label}<small>${shift.start} → ${shift.end}</small></button>`).join('');
  const list = $('#line-list'); list.innerHTML = ''; $('#empty-state').hidden = state.lines.length > 0; $('#dashboard-help').textContent = state.lines.length ? `${state.lines.length}/10 ligne${state.lines.length > 1 ? 's' : ''} configurée${state.lines.length > 1 ? 's' : ''}.` : 'Configurez une ligne pour commencer.';
  state.lines.forEach((line) => { const card = $('#line-card-template').content.firstElementChild.cloneNode(true); const duration = cycleDurationMs(line.length, line.speed); const projection = line.startAt ? projectCycles({ startAt: line.startAt, durationMs: duration, shiftEnd: window.end }) : null; card.dataset.id = line.id; card.querySelector('.line-name').textContent = `L${line.lineNumber}`; card.querySelector('.line-config').textContent = `${line.length} m · ${line.speed} m/min · ${line.coilsPerCycle} bobines`; card.querySelector('.cycle-duration').textContent = formatDuration(duration); card.querySelector('.started-at').textContent = line.startAt ? formatClock(line.startAt) : 'Non démarré'; card.querySelector('.next-end').textContent = line.startAt ? formatClock(nextCycleEnd(line)) : '—';
    const pill = card.querySelector('.status-pill'); const msg = card.querySelector('.line-message');
    if (projection?.status) { pill.textContent = projection.status.label; pill.classList.add(projection.status.className); card.querySelector('.final-margin').textContent = formatDuration(projection.marginMs); msg.textContent = `Dernier cycle terminé à ${formatClock(projection.cycles.filter(c => !c.exceedsShift).at(-1).end)}.`; } else if (line.startAt) { pill.textContent = 'À RECALER'; pill.classList.add('neutral'); card.querySelector('.final-margin').textContent = 'Aucun cycle terminé'; msg.textContent = 'Le cycle en cours dépasse la fin du poste.'; } else { pill.textContent = 'EN ATTENTE'; pill.classList.add('neutral'); card.querySelector('.final-margin').textContent = '—'; msg.textContent = 'Lancez le cycle pour obtenir la projection.'; }
    if (projection) {
      card.querySelector('.projection-panel').hidden = false;
      card.querySelector('.projection-list').innerHTML = projection.cycles.map((cycle) => `<li class="${cycle.highlighted ? `highlight ${cycle.status.className}` : ''} ${cycle.exceedsShift ? 'exceeds' : ''}"><strong>Cycle ${cycle.number}</strong><span>${formatClock(cycle.start)} → ${formatClock(cycle.end)}</span>${cycle.exceedsShift ? '<em>Dépassement du poste</em>' : cycle.highlighted ? `<em>${cycle.status.label}</em>` : ''}</li>`).join('');
      card.querySelector('.start-button').textContent = '↻ CYCLE RELANCÉ';
    }
    list.append(card);
  });
}
function openForm(line = null) { editingId = line?.id || null; const f = $('#line-form'); f.reset(); $('#dialog-title').textContent = line ? `Modifier L${line.lineNumber}` : 'Configurer une ligne'; $('#form-kicker').textContent = line ? 'PARAMÈTRES LIGNE' : 'NOUVELLE LIGNE'; $('#delete-line').hidden = !line; if (line) Object.entries(line).forEach(([key, value]) => f.elements[key] && (f.elements[key].value = value)); updatePreview(); $('#line-dialog').showModal(); }
function updatePreview() { const f = $('#line-form'); const length = f.elements.length.value; const speed = f.elements.speed.value; $('#duration-preview').textContent = length > 0 && speed > 0 ? `Durée calculée : ${formatDuration(cycleDurationMs(length, speed))}` : 'La durée du cycle apparaîtra ici.'; }
function showDetails(id) { const line = lineById(id); const window = getShiftWindow(state.shiftId); const p = projectCycles({ startAt: line.startAt, durationMs: cycleDurationMs(line.length, line.speed), shiftEnd: window.end }); $('#detail-content').innerHTML = `<div class="dialog-header"><div><p class="eyebrow">PROJECTION</p><h2>L${line.lineNumber}</h2></div><button class="close-button close-detail" aria-label="Fermer">×</button></div><p class="detail-intro">Départ enregistré à <strong>${formatClock(line.startAt)}</strong> · fin de poste <strong>${window.end.getHours().toString().padStart(2,'0')}:${window.end.getMinutes().toString().padStart(2,'0')}</strong></p><ol class="cycle-list">${p.cycles.map(c => `<li class="${c.highlighted ? `highlight ${c.status.className}` : ''} ${c.exceedsShift ? 'exceeds' : ''}"><b>Cycle ${c.number}</b><span>${formatClock(c.start)} → ${formatClock(c.end)}</span>${c.exceedsShift ? '<em>Dépassement du poste</em>' : c.highlighted ? `<em>${c.status.label}</em>` : ''}</li>`).join('')}</ol><div class="detail-footer">${p.status ? `<span class="status-pill ${p.status.className}">${p.status.label}</span><strong>Marge finale : ${formatDuration(p.marginMs)}</strong>` : '<strong>Aucun cycle ne termine avant la relève.</strong>'}</div>`; $('#detail-dialog').showModal(); }
$('#shift-options').addEventListener('click', (e) => { const button = e.target.closest('[data-shift]'); if (button) { state.shiftId = button.dataset.shift; save(); render(); } });
$('#add-line').onclick = () => state.lines.length < 10 && openForm(); document.querySelector('.add-line-action').onclick = () => openForm();
$('#close-dialog').onclick = $('#cancel-dialog').onclick = () => $('#line-dialog').close(); $('#line-form').addEventListener('input', updatePreview);
$('#line-form').addEventListener('submit', (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); const data = Object.fromEntries(f); const line = { id: editingId || crypto.randomUUID(), lineNumber: Number(data.lineNumber), length: Number(data.length), speed: Number(data.speed), coilsPerCycle: Number(data.coilsPerCycle), startAt: editingId ? lineById(editingId).startAt : null }; if (editingId) state.lines = state.lines.map((x) => x.id === editingId ? line : x); else state.lines.push(line); save(); $('#line-dialog').close(); render(); });
$('#delete-line').onclick = () => { state.lines = state.lines.filter((line) => line.id !== editingId); save(); $('#line-dialog').close(); render(); };
$('#line-list').addEventListener('click', (e) => { const card = e.target.closest('.line-card'); if (!card) return; const line = lineById(card.dataset.id); if (e.target.closest('.start-button')) { line.startAt = Date.now(); save(); render(); } else if (e.target.closest('.complete-button')) { line.startAt = Date.now(); save(); render(); } else if (e.target.closest('.open-details')) { line.startAt ? showDetails(line.id) : openForm(line); } });
$('#detail-dialog').addEventListener('click', (e) => { if (e.target.classList.contains('close-detail') || e.target === $('#detail-dialog')) $('#detail-dialog').close(); });
window.addEventListener('beforeinstallprompt', (e) => { e.preventDefault(); installPrompt = e; $('#install-button').hidden = false; }); $('#install-button').onclick = async () => { await installPrompt?.prompt(); $('#install-button').hidden = true; };
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js'); render(); setInterval(render, 30_000);
