import { SHIFTS, cycleDurationMs, formatDuration, formatClock, getShiftWindow, projectCycles, nextCycleEnd, resolveManualTime } from './calculations.js';

const KEY = 'application-bobines-v1'; const STOP_REASONS = ['Panne machine', 'Réglage', 'Changement matière', 'Contrôle qualité', 'Manque matière', 'Autre'];
const $ = (s) => document.querySelector(s); const now = () => Date.now();
function migrate(raw) { const base = raw && typeof raw === 'object' ? raw : {}; return { shiftId: base.shiftId || 'morning', operatorNumber: String(base.operatorNumber || '1073'), events: Array.isArray(base.events) ? base.events : [], lines: Array.isArray(base.lines) ? base.lines.map((line) => ({ ...line, productionHistory: Array.isArray(line.productionHistory) ? line.productionHistory : [], production: line.production || (line.startAt ? { id: crypto.randomUUID(), startAt: line.startAt, pauses: [], endAt: null } : null) })) : [] }; }
let state = migrate(JSON.parse(localStorage.getItem(KEY) || 'null')); let editingId = null; let installPrompt; let pendingEvent = null;
const save = () => localStorage.setItem(KEY, JSON.stringify(state)); const lineById = (id) => state.lines.find((line) => line.id === id);
function eventFor(line, type, declaredAt, extra = {}) { state.events.push({ id: crypto.randomUUID(), recordedAt: now(), declaredAt, type, lineNumber: line.lineNumber, operatorNumber: state.operatorNumber, production: { length: line.length, speed: line.speed, coilsPerCycle: line.coilsPerCycle }, ...extra }); }
function currentProduction(line) { return line.production || (line.startAt ? { id: crypto.randomUUID(), startAt: line.startAt, pauses: [], endAt: null } : null); }
function render() {
  const window = getShiftWindow(state.shiftId); $('#shift-range').textContent = `${window.start} → ${window.end}`.replace(/.*?(\d{2}:\d{2}).*?(\d{2}:\d{2}).*/, '$1 → $2'); $('#operator-number').value = state.operatorNumber;
  $('#shift-options').innerHTML = SHIFTS.map((shift) => `<button class="shift-option ${shift.id === state.shiftId ? 'selected' : ''}" data-shift="${shift.id}" role="radio" aria-checked="${shift.id === state.shiftId}">${shift.label}<small>${shift.start} → ${shift.end}</small></button>`).join('');
  const list = $('#line-list'); list.innerHTML = ''; $('#empty-state').hidden = state.lines.length > 0; $('#dashboard-help').textContent = state.lines.length ? `${state.lines.length}/10 ligne${state.lines.length > 1 ? 's' : ''} configurée${state.lines.length > 1 ? 's' : ''}.` : 'Configurez une ligne pour commencer.';
  state.lines.forEach((line) => { const card = $('#line-card-template').content.firstElementChild.cloneNode(true); const duration = cycleDurationMs(line.length, line.speed); const production = currentProduction(line); const projection = production ? projectCycles({ startAt: production.startAt, durationMs: duration, shiftEnd: window.end, pauses: production.pauses || [], stoppedAt: production.endAt }) : null; const active = production && !production.endAt; const paused = active && production.pausedAt;
    card.dataset.id = line.id; card.querySelector('.line-name').textContent = `L${line.lineNumber}`; card.querySelector('.line-config').textContent = `${line.length} m · ${line.speed} m/min · ${line.coilsPerCycle} bobines`; card.querySelector('.cycle-duration').textContent = formatDuration(duration); card.querySelector('.started-at').textContent = production ? formatClock(production.startAt) : 'Non démarré'; card.querySelector('.next-end').textContent = active ? (paused ? 'En pause' : (nextCycleEnd(production, duration) ? formatClock(nextCycleEnd(production, duration)) : '—')) : '—'; card.querySelector('.last-end').textContent = projection?.cycles.at(-1) ? formatClock(projection.cycles.at(-1).end) : '—';
    const pill = card.querySelector('.status-pill'); const msg = card.querySelector('.line-message'); if (projection?.status) { pill.textContent = production.endAt ? 'OF TERMINÉ' : paused ? 'EN PAUSE' : projection.status.label; pill.classList.add(production.endAt || paused ? 'neutral' : projection.status.className); card.querySelector('.final-margin').textContent = formatDuration(projection.marginMs); msg.textContent = production.endAt ? `OF terminé à ${formatClock(production.endAt)}.` : paused ? `Pause depuis ${formatClock(production.pausedAt)}.` : projection.nextImpossible ? 'Prochain cycle impossible à terminer avant la relève.' : `Dernière fin prévue à ${formatClock(projection.cycles.at(-1).end)}.`; } else { pill.textContent = production?.endAt ? 'OF TERMINÉ' : paused ? 'EN PAUSE' : 'EN ATTENTE'; pill.classList.add('neutral'); card.querySelector('.final-margin').textContent = '—'; msg.textContent = production?.endAt ? `OF terminé à ${formatClock(production.endAt)}.` : paused ? `Pause depuis ${formatClock(production.pausedAt)}.` : 'Lancez le cycle pour obtenir la projection.'; }
    if (projection) { card.querySelector('.projection-panel').hidden = false; card.querySelector('.projection-list').innerHTML = projection.cycles.map((cycle) => `<li class="${cycle.highlighted ? `highlight ${cycle.status.className}` : ''}"><strong>Cycle ${cycle.number}</strong><span>${formatClock(cycle.start)} → ${formatClock(cycle.end)}</span>${cycle.highlighted ? `<em>${cycle.status.label}</em>` : ''}</li>`).join(''); }
    card.querySelector('.start-actions').hidden = Boolean(production); card.querySelector('.active-actions').hidden = !production; card.querySelector('.pause-button').hidden = !active || paused; card.querySelector('.resume-button').hidden = !paused; card.querySelector('.correct-start-button').hidden = !active; card.querySelector('.complete-button').hidden = !active; card.querySelector('.restart-button').hidden = !active; card.querySelector('.end-of-button').hidden = !active; card.querySelector('.new-of-button').hidden = !production?.endAt; list.append(card);
  });
}
function openForm(line = null) { editingId = line?.id || null; const f = $('#line-form'); f.reset(); $('#dialog-title').textContent = line ? `Modifier L${line.lineNumber}` : 'Configurer une ligne'; $('#form-kicker').textContent = line ? 'PARAMÈTRES LIGNE' : 'NOUVELLE LIGNE'; $('#delete-line').hidden = !line; if (line) Object.entries(line).forEach(([key, value]) => f.elements[key] && (f.elements[key].value = value)); updatePreview(); $('#line-dialog').showModal(); }
function updatePreview() { const f = $('#line-form'); $('#duration-preview').textContent = f.elements.length.value > 0 && f.elements.speed.value > 0 ? `Durée calculée : ${formatDuration(cycleDurationMs(f.elements.length.value, f.elements.speed.value))}` : 'La durée du cycle apparaîtra ici.'; }
function openEvent(line, type) { pendingEvent = { line, type }; const form = $('#event-form'); form.reset(); $('#event-error').hidden = true; const labels = { startManual: 'Saisir l’heure de départ', correctStart: 'Corriger l’heure de départ', pause: 'Arrêt / pause', resume: 'Reprise', endOf: 'Fin d’OF' }; $('#event-title').textContent = labels[type]; $('#event-kicker').textContent = `L${line.lineNumber} · OPÉRATEUR ${state.operatorNumber}`; $('#reason-label').hidden = type !== 'pause'; $('#event-time-label').firstChild.textContent = type === 'correctStart' ? 'Nouvelle heure de départ' : 'Heure déclarée'; form.elements.time.value = new Date().toTimeString().slice(0, 5); $('#event-dialog').showModal(); }
function start(line, declaredAt, type = 'start') { if (line.production?.endAt) line.productionHistory = [...(line.productionHistory || []), line.production]; line.production = { id: crypto.randomUUID(), startAt: declaredAt, pauses: [], endAt: null }; line.startAt = declaredAt; eventFor(line, type, declaredAt); save(); render(); }
function showDetails(id) { const line = lineById(id); const production = currentProduction(line); if (!production) return openForm(line); const window = getShiftWindow(state.shiftId); const p = projectCycles({ startAt: production.startAt, durationMs: cycleDurationMs(line.length, line.speed), shiftEnd: window.end, pauses: production.pauses || [], stoppedAt: production.endAt }); $('#detail-content').innerHTML = `<div class="dialog-header"><div><p class="eyebrow">PROJECTION</p><h2>L${line.lineNumber}</h2></div><button class="close-button close-detail" aria-label="Fermer">×</button></div><p class="detail-intro">Départ enregistré à <strong>${formatClock(production.startAt)}</strong> · fin de poste <strong>${formatClock(window.end)}</strong></p><ol class="cycle-list">${p.cycles.map(c => `<li class="${c.highlighted ? `highlight ${c.status.className}` : ''}"><b>Cycle ${c.number}</b><span>${formatClock(c.start)} → ${formatClock(c.end)}</span></li>`).join('')}</ol><div class="detail-footer"><strong>${p.status ? `Marge finale : ${formatDuration(p.marginMs)}` : 'Aucun cycle complet avant la relève.'}</strong></div>`; $('#detail-dialog').showModal(); }
$('#operator-number').addEventListener('change', (e) => { state.operatorNumber = e.target.value.trim() || '1073'; save(); render(); }); $('#shift-options').addEventListener('click', (e) => { const b = e.target.closest('[data-shift]'); if (b) { state.shiftId = b.dataset.shift; save(); render(); } });
$('#add-line').onclick = () => state.lines.length < 10 && openForm(); document.querySelector('.add-line-action').onclick = () => openForm(); $('#close-dialog').onclick = $('#cancel-dialog').onclick = () => $('#line-dialog').close(); $('#line-form').addEventListener('input', updatePreview);
$('#line-form').addEventListener('submit', (e) => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); const old = editingId && lineById(editingId); const line = { id: editingId || crypto.randomUUID(), lineNumber: Number(data.lineNumber), length: Number(data.length), speed: Number(data.speed), coilsPerCycle: Number(data.coilsPerCycle), startAt: old?.startAt || null, production: old?.production || null, productionHistory: old?.productionHistory || [] }; if (editingId) state.lines = state.lines.map((x) => x.id === editingId ? line : x); else state.lines.push(line); save(); $('#line-dialog').close(); render(); }); $('#delete-line').onclick = () => { state.lines = state.lines.filter((line) => line.id !== editingId); save(); $('#line-dialog').close(); render(); };
$('#line-list').addEventListener('click', (e) => { const card = e.target.closest('.line-card'); if (!card) return; const line = lineById(card.dataset.id); if (e.target.closest('.start-now-button')) start(line, now()); else if (e.target.closest('.manual-start-button')) openEvent(line, 'startManual'); else if (e.target.closest('.correct-start-button')) openEvent(line, 'correctStart'); else if (e.target.closest('.pause-button')) openEvent(line, 'pause'); else if (e.target.closest('.resume-button')) openEvent(line, 'resume'); else if (e.target.closest('.end-of-button')) openEvent(line, 'endOf'); else if (e.target.closest('.new-of-button')) start(line, now(), 'cycle-relance'); else if (e.target.closest('.restart-button')) start(line, now(), 'cycle-relance'); else if (e.target.closest('.complete-button')) { eventFor(line, 'cycle-termine', now()); save(); render(); } else if (e.target.closest('.open-details')) showDetails(line.id); });
$('#close-event').onclick = $('#cancel-event').onclick = () => $('#event-dialog').close(); $('#event-form').addEventListener('submit', (e) => { e.preventDefault(); const { line, type } = pendingEvent; try { const declaredAt = resolveManualTime(new FormData(e.currentTarget).get('time'), getShiftWindow(state.shiftId), now()); const p = currentProduction(line); if (type === 'startManual') start(line, declaredAt); else if (type === 'correctStart') { p.startAt = declaredAt; line.startAt = declaredAt; eventFor(line, 'correction-depart', declaredAt); save(); render(); } else if (type === 'pause') { if (declaredAt < p.startAt) throw new Error('L’arrêt ne peut pas précéder le départ.'); p.pausedAt = declaredAt; p.pauses.push({ startAt: declaredAt, endAt: null, reason: new FormData(e.currentTarget).get('reason') || STOP_REASONS[0] }); eventFor(line, 'pause', declaredAt, { reason: p.pauses.at(-1).reason }); save(); render(); } else if (type === 'resume') { const pause = p.pauses.at(-1); if (declaredAt < pause.startAt) throw new Error('La reprise ne peut pas précéder le début de l’arrêt.'); pause.endAt = declaredAt; p.pausedAt = null; eventFor(line, 'reprise', declaredAt, { pauseDurationMs: declaredAt - pause.startAt, reason: pause.reason }); save(); render(); } else if (type === 'endOf') { if (declaredAt < p.startAt) throw new Error('La fin d’OF ne peut pas précéder le départ.'); p.endAt = declaredAt; eventFor(line, 'fin-of', declaredAt); save(); render(); } $('#event-dialog').close(); } catch (error) { $('#event-error').textContent = error.message; $('#event-error').hidden = false; } });
$('#detail-dialog').addEventListener('click', (e) => { if (e.target.classList.contains('close-detail') || e.target === $('#detail-dialog')) $('#detail-dialog').close(); }); window.addEventListener('beforeinstallprompt', (e) => { e.preventDefault(); installPrompt = e; $('#install-button').hidden = false; }); $('#install-button').onclick = async () => { await installPrompt?.prompt(); $('#install-button').hidden = true; }; if ('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js'); render(); setInterval(render, 30_000);
